config/routes.rb
Rails.application.routes.draw do
  root to: "kingdoms#index"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"

  resources :kingdoms, only: %i(index new create show) do
    member do
      post :upvote
    end
  end
  resources :cards, only: %i(index)
  resources :plays, only: %i(new create)

  get :credits, to: "application#credits"
  get :admin, to: "application#admin"
  get :graphql_test, to: "kingdoms#graphql_test"
end

app/models/kingdom.rb
# == Schema Information
#
# Table name: kingdoms
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string
#  updated_at :datetime         not null
#

class Kingdom < ApplicationRecord
  has_many :kingdom_memberships, dependent: :destroy
  has_many :cards, through: :kingdom_memberships
  has_many :plays, dependent: :destroy

  validates :name, presence: true
  # validate :validate_kindom_size

  def play_count
    plays.count
  end

  def rating
    plays.average(:rating).to_i.ceil
  end

  def materials
    dependencies_by_type[Material] || []
  end

  def supply_cards
    all_cards.select(&:supply?)
  end

  def non_supply_cards
    all_cards.reject(&:supply?)
  end

  def all_cards
    cards + card_dependencies
  end

  def card_dependencies
    dependencies_by_type[Card] || []
  end

  def card_ids
    cards.pluck(:id)
  end

  private

  def validate_kindom_size
    errors.add(:cards, "must contain exactly 10 cards") if cards.size != 10
  end

  def dependencies_by_type
    @dependencies_by_type ||= cards.map(&:dependencies).flatten.uniq.group_by(&:class)
  end
end

app/controllers/kingdoms_controller.rb
class KingdomsController < ApplicationController
  def index
    render :index, locals: {
      kingdoms: Kingdom.all.includes(:cards)
    }
  end

  def new
    render :new, locals: {
      cards: Card.all,
      kingdom: Kingdom.new
    }
  end

  def create
    kingdom = Kingdom.new(kingdom_params)
    if kingdom.save
      redirect_to kingdom_path(kingdom), notice: "Your kingdom was created successfully"
    else
      render :new, locals: {
        cards: Card.all,
        kingdom: kingdom
      }
    end
  end

  def show
    kingdom = Kingdom.find(params[:id])
    render :show, locals: {
      kingdom: kingdom,
      play: Play.new(kingdom: kingdom)
    }
  end

  def graphql_test
    render :graphql_test
  end

  private

  def kingdom_params
    params.require(:kingdom).permit(
      :name,
      card_ids: []
    )
  end
end

app/views/kingdoms/_form.html.erb
<%=
  react_component("KingdomForm",
    authenticityToken: form_authenticity_token,
    cards: cards,
    kingdom: kingdom,
    submitEndpoint: kingdom.persisted? ? kingdom_path(kingdom) : kingdoms_path,
    submitVerb: kingdom.persisted? ? 'put' : 'post',
  )
%>

app/views/kingdoms/graphql_test.html.erb
<div id="root"></div>
<%= javascript_pack_tag 'graphql_test' %>

app/views/kingdoms/index.html.erb
<h1 class="h-inline">Kingdoms</h1>

<%= button_to "New Kingdom", new_kingdom_path, method: :get, form_class: "c-btn--main h-inline h-float--right" %>

<%= react_component("KingdomsList", kingdoms: kingdoms) %>

app/views/kingdoms/new.html.erb
<h1>New Kingdom</h1>
<%= render "form", kingdom: kingdom, cards: cards %>

app/views/kingdoms/show.html.erb
<h1><%= kingdom.name %></h1>
<p>Average Rating: <%= kingdom.rating %></p>
<%# TODO %>
<p>Number of games played: <%= kingdom.plays.count %>

<div class="l-container l-container--centered l-kingdom-show">

  <div class="l-kingdom-show__kingdom">
    <%= react_component("Kingdom", kingdom: kingdom, show_header: false) %>
  </div>

  <div class="l-kingdom-show__rating-form">
    <%= render "plays/form", play: play %>
  </div>
</div>