config/routes.rb
Rails.application.routes.draw do
  root to: "kingdoms#index"

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"

  resources :kingdoms, only: %i(index new create show) do
    member do
      post :upvote
    end
  end
  resources :cards, only: %i(index)
  resources :plays, only: %i(new create)

  get :credits, to: "application#credits"
  get :admin, to: "application#admin"
  get :graphql_test, to: "kingdoms#graphql_test"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def credits; end

  def admin; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% if notice %>
  <p class="c-flash c-flash--notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="c-flash c-flash--alert"><%= alert %></p>
<% end %>

app/views/application/_footer.html.erb
<div class="l-footer">
  <%= link_to 'Credits', credits_path %>
</div>

app/views/application/_header.html.erb
<div class="l-header">
  <%= link_to 'Fairgrounds', root_path, class: 'l-header__link' %>
</div>
<%= render 'flash' %>

app/views/application/admin.html.erb
<div id="root"></div>
<%= javascript_pack_tag 'react-admin' %>

app/views/application/credits.html.erb
<h1>Credits</h1>

<div class="l-container">
  <ul>
    <li>
      The web application itself was created by me,
      <a href="http://github.com/dkniffin">dkniffin<a>.
      However, it is open source and you can find the source at
      <a href="https://github.com/dkniffin/fairgrounds">https://github.com/dkniffin/fairgrounds</a>.
      I would love if you contribute pull requests to it.
    </li>
    <li>
      All card images were pulled from
      <a href="http://wiki.dominionstrategy.com/">wiki.dominionstrategy.com</a>
    </li>
    <li>
      For a list of card illustrators, see
      <a href="http://wiki.dominionstrategy.com/index.php/List_of_illustrators">this wiki page</a>
    </li>
    <li>
      All icons are from <a href="https://fontawesome.com/">Font Awesome</a>
    </li>
  </ul>
</div>